spring:
  h2:
    console:
      enabled: true
  data:
    rest:
      detection-strategy: annotated

management:
  port: 8081
  metrics:
    export:
      wavefront:
        enabled: ${WAVEFRONT_ENABLE:false}
        global-prefix: spring
        uri: proxy://${WAVEFRONT_URI:localhost:2878}
        step: 30s
  security:
    enabled: false
  
